#!/bin/sh /etc/rc.common
START=99

start() {
    nohup /usr/bin/jwclient start |
    awk '{ getDate="date +\[%Y/%m/%d-%H:%M:%S\]"; getDate | getline date; printf "%s %s\n", date, $0; close(getDate) }' >> \
    /var/log/jwclient.log &
}

stop() {
    /usr/bin/jwclient stop
}